import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/home.module.scss";

import Gradient from "@/components/Gradient";
import Intro from "@/components/Intro";
import Menu from "@/components/Menu";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Gradient blur />
        <div className={styles.center}>
          <div className={styles.container}>
            <Gradient />
            <Intro />
          </div>
        </div>
        <Menu />
      </main>
    </>
  );
}
